### PR TITLE
kscreengenie the new KDE Screenshot tool replace Ksnapshot, remove ksnapshot

### PR DESCRIPTION
**Pull request by groni**

### CODE REVIEW

**Comment by ertugerata** [comment]
Pls rm ksnapshot in repo main, if that package is remplacement

**Comment by groni** [comment]
ok


2015-09-30 6:32 GMT+02:00 Ertuğrul Erata <notifications@github.com>:

**Comment by ertugerata** [comment]
add libkscreen-devel and xcb-util-cursor-devel in builddep, fix keybord shortcut and pr again...

**Comment by groni** [comment]
ok


2015-09-30 21:33 GMT+02:00 Ertuğrul Erata <notifications@github.com>:

**Pull request merged**
